using Framework.Debugging;

/// <summary>
/// Class used for the management of timer instances
/// </summary>
public static class Timer
{
    /// <summary>
    /// Starts a new timer that executes the action when it finishes
    /// </summary>
    public static void StartNew(int hours, int minutes, TimerAction action)
    {
        if (hours < 0 || minutes < 0)
        {
            Debugger.Log(LOG_TYPE.ERROR,
                "Time < 0\nNo timer was started!");

            return;
        }

        var timer = new TimerInstance(hours, minutes, action);
        TimeManager.Instance.RegisterTimer(timer);
    }
}

/// <summary>
/// Implementation of the timer generated by the Timer class
/// </summary>
internal class TimerInstance
{
    #region Variables

    private int _targetTime;
    private int _timeUnit;
    private TimerAction _action;

    #endregion

    #region Constructors

    public TimerInstance(int hours, int minutes, TimerAction action)
    {
        _timeUnit = -1;
        _targetTime = minutes % 60 + hours * 60;
        _action = action;

        Tick();
    }

    #endregion

    /// <summary>
    /// Advances the timer and executes the action
    /// </summary>
    public void Tick()
    {
        ++_timeUnit;

        if (_timeUnit == _targetTime)
        {
            _action();
            TimeManager.Instance.UnregisterTimer(this);
        }
    }
}